### ISSUE TITLE
Retreiwving Projects

### ISSUE THREAD

**Issue by craigvc** [GrahamCampbell/Laravel-GitLab#11]
Hi, I apologise if this is a dumb question!
I call am using this code

```
<?php

namespace App\Http\Controllers\API\Integrations\GitLab;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use GrahamCampbell\GitLab\Facades\GitLab;
use GrahamCampbell\GitLab\GitLabManager;

class GitLabsController extends Controller
{

    function __construct() {
		 }




public function index(){
   

$projects = GitLab::Projects();
 return response()->json($projects);

}
}
```
in my controller (I have put my access token in the config settings)
but its returning an empty array,
Can you advise what I am doing wrong?

**Comment by ijaureguialzo** [comment]
You have to complete the request, it should be:

```php
$projects = GitLab::Projects()->all();
```

Also, you could add a where() and then get(). See: https://laravel.com/docs/5.8/eloquent#retrieving-models

**Comment by GrahamCampbell** [comment]
> Also, you could add a where() and then get(). See: laravel.com/docs/5.8/eloquent#retrieving-models

GitLab is not an eloquent model.

**Comment by GrahamCampbell** [comment]
The GitLab facade calls operates on an instance of `Gitlab\Client`. Please take a look at the code for that to see what is callable from there.

**Comment by GrahamCampbell** [comment]
There are also some examples in the readme.
