### ISSUE TITLE
Creating issues in a project

### ISSUE THREAD

**Issue by ghost** [GrahamCampbell/Laravel-GitLab#14]
How do I create an issue with this package? 
I can retrieve the correct project as an array, but it shows as an array, rather than `\Gitlab\Models\Project`. so I can't call the `createIssue` method.

I retrieved the project like this. because there wasn't a "find by id" either. at least not from what I could see in the documentation.

```php
collect($this->manager->projects()->all())->firstWhere('id', $projectId)
```

Thanks

**Comment by GrahamCampbell** [comment]
The method you want is `show`. When in doubt, always just have a look a the source code. :)

https://github.com/m4tthumphrey/php-gitlab-api/blob/9.13.0/lib/Gitlab/Api/Projects.php#L90-L114

**Comment by ghost** [comment]
That still returns an array, not the model :/

**Comment by GrahamCampbell** [comment]
It looks like, from the source code, that `all()` also returns an array?

**Comment by ghost** [comment]
Let me clarify:
show() returns the result from the get request. get() returns the json result as an associative array. when I `dump` the result of `$manager->projects()->find($projectId)` it returns the json result from gitlab as an associative array, not the resulting model. Is there any way using this package to convert it to the model?

**Comment by GrahamCampbell** [comment]
It looks like there is, but it's a bit messy: https://github.com/m4tthumphrey/php-gitlab-api/blob/9.13.0/lib/Gitlab/Model/Project.php#L69-L88.

**Comment by GrahamCampbell** [comment]
```php
$client = $this->manager->connection();
$project = Gitlab\Model\Project::fromArray($client, $client->projects()->show($projectId));
```

**Comment by ghost** [comment]
Thanks! that worked :)
