### ISSUE TITLE
Documentation on config/gitlab.php

### ISSUE THREAD

**Issue by challapradyumna** [GrahamCampbell/Laravel-GitLab#17]
Should the token be of one of the admin?
Can you explain more about the other options available , OAuth flow?

**Comment by GrahamCampbell** [comment]
This package does not do oauth flow. Please use another standard oauth2 implementation.

**Comment by GrahamCampbell** [comment]
For the token mode, provide an access token, for oauth mode provide an oauth2 token that has been generated by some means. It's normal for this to be done programmatically, rather than hard coding in config.

**Comment by GrahamCampbell** [comment]
There are lots of resources for PHP OAuth 2 flow: https://www.google.com/search?q=php+oauth2+flow.
