### ISSUE TITLE
No option to get a merge request's pipelines

### ISSUE THREAD

**Issue by FakeSe** [GrahamCampbell/Laravel-GitLab#19]
in the gitlab Api we can get a merge request's pipelines (in order to know the MR's build status for example)
Something like this in "MergeRequests.php":

`    /**

     * @param int $project_id

     * @param int $mr_id

     * @return mixed

     */

    public function pipelines($project_id, $mr_id)
    {

        return $this->get($this->getProjectPath($project_id, 'merge_requests/'.
      $this->encodePath($mr_id).'/pipelines'));

    }
`

**Comment by GrahamCampbell** [comment]
Please get in touch with the upstream library. We're just a Laravel bridge. :)
