### ISSUE TITLE
Organization for Laravel-Gitlab

### ISSUE THREAD

**Issue by allcreatures** [GrahamCampbell/Laravel-GitLab#2]
To avoid change repo urls, could an organization be made for this repo and put there?

**Comment by GrahamCampbell** [comment]
How do you mean?

**Comment by allcreatures** [comment]
Should a new maintainer be needed down the road, presumably the URL for this repository would change again. If a Github Organization was created for Laravel-Gitlab, and the repository put in organization, it would allow for new maintainers without having to move the repository to a new account. Disclaimer: Under the new pricing structure for Github, I'm not sure if there is now a cost associated with organizations.

**Comment by GrahamCampbell** [comment]
This is a brand new package. I don't plan on dropping it immediately. :)

**Comment by GrahamCampbell** [comment]
If this package ever was to move in the future, it wouldn't matter, since both github.com and api.github.com forward requests to the new location.

**Comment by GrahamCampbell** [comment]
The reason I put this package here, and not on a new orgaization, and the reason I dont't move my laravel packages to an organization is beause of the exposure. People find my packages much easier to find on my own account, than on an organization they've never heard off.

**Comment by allcreatures** [comment]
Thanks for the clarification Graham. All is good.
