### ISSUE TITLE
Ease the usage of webhooks

### ISSUE THREAD

**Issue by spawnia** [GrahamCampbell/Laravel-GitLab#20]
I saw this was discussed previously in https://github.com/GrahamCampbell/Laravel-GitLab/issues/16. It is true that webhook usage is not hard, although this library could make it easier by adding a clear path on how it can be implemented.

The controller method you suggested in https://github.com/GrahamCampbell/Laravel-GitLab/issues/16#issuecomment-510197294 seems like a great idea. Are you open to adding that into the library, together with a bit of documentation around how to use it?

Ideas for further improvement:
- Have separate events for each webhook type
- Add a small testing helper

I would be willing to provide a PR.

**Comment by GrahamCampbell** [comment]
I'm not sure I want to include this in the library. Thanks for the suggestion, though.
