### ISSUE TITLE
Wait for a fork to complete

### ISSUE THREAD

**Issue by ijaureguialzo** [GrahamCampbell/Laravel-GitLab#22]
Hello, I'm trying to execute actions after a fork is completed, but can't find a way of waiting for the call to complete.

I want to do this:

```php
$fork = GitLab::projects()->fork($original['id'], [
    'namespace' => trim($destino, '/'),
    'name' => $nombre,
    'path' => Str::slug($ruta)
]);

// Desconectarlo del repositorio original
GitLab::projects()->removeForkRelation($fork['id']);
```

Is there any way of doing this?

Thank you in advance for your help.

**Comment by GrahamCampbell** [comment]
I guess you can just sleep in a while loop until you can no longer see the repo?

**Comment by ijaureguialzo** [comment]
I can, but the removeFork() operation raises an exception because GitLab takes some time to do the fork and was wondering if I can get some type of callback when it completes the fork.

Just trying to figure out how to chain operations after the fork without having to ignore the exceptions and keep waiting.

**Comment by GrahamCampbell** [comment]
No, unfortunately not. GitLab's API is not great anyway, in that there is a delay of up to 10 seconds before state changes actually show up on the API, for GET requests, but POST requests will see the actual state.

**Comment by GrahamCampbell** [comment]
This is because they use slave databases to serve read-only requests, and replication takes some time...

**Comment by ijaureguialzo** [comment]
Ok, thank you. Will stick to the while() loop.
