### ISSUE TITLE
Set oauth dynamically by logged in user

### ISSUE THREAD

**Issue by lordhasyim** [GrahamCampbell/Laravel-GitLab#27]
Hello, 

i've try delete user either from projects or from group. but always get 404 not found.

```
$project = Gitlab::Projects()->show($projectId);
$projectPermissions = $project['permissions'];
$groupId = $project['namespace']['parent_id'];

 if ( empty($projectPermissions['project_access']) && !empty($projectPermissions['group_access'])) {
                
                // delete from group member
                try {
                    Gitlab::Groups()->removeMember($groupId, $userId);
                    $removed[] = "remove user id : " . $userId . " from group id : " . $projectId;
                } catch(\Exception $e) {
                    $removed[] =  $e->getMessage(); 
                }
 } else if ( empty($projectPermissions['group_access']) && !empty($projectPermissions['project_access'])) {
                //delete from project member
                try {
                    Gitlab::Projects()->removeMember($projectId, $userId);
                    $removed[] = "remove user id : " . $userId . " from project id : " . $projectId;
                } catch(\Exception $e) {
                    $removed[] = $e->getMessage();
                    
                }
            }
```
i try curl also
![Screenshot_20200903_163017_edit](https://user-images.githubusercontent.com/3645452/92504019-45b20980-f22c-11ea-9fe2-a8beb39f4b99.png)

is it permission problem?, then i found the second problem.

i've been read the docs, but i don't now how to set oauth dynamic by user or is it possible, or maybe i have wrong logic in my mind?

i have a case user login via oauth token, and use the token from logged in user oauth token for accessing gitlab repo. 
so by those token we can use it as for managing repo. 
my problem is every user login and the app still use my user as a basis. so even the project owner or group owner can't delete member. the error says 404.
i've been set the connection in config/gitlab.php

```
'connections' => [

        'main' => [
            'token'   => i set this with my private token',
            'method'  => 'token',
        ],

        'alternative' => [
            'token'   => 'your-token', <- how to set this dynamically by logged in user after redirect callback
            'method'  => 'oauth',
        ],

    ],

```

how to set oauth token dynamically?

if been try
```
       $client = Gitlab::authenticate($getInfo->token, 'oauth_token');
```
still not work.

thank you for your answer.

**Comment by GrahamCampbell** [comment]
You can use the factory class to create the instance you need: https://github.com/GrahamCampbell/Laravel-GitLab/blob/4.0/src/GitLabFactory.php. Very similar to https://github.com/GrahamCampbell/Laravel-GitHub/issues/91. :)

**Comment by lordhasyim** [comment]
thank you for your quick answer....
