### ISSUE TITLE
Usage with GitLab\ResultPager

### ISSUE THREAD

**Issue by spawnia** [GrahamCampbell/Laravel-GitLab#28]
We recently crossed the threshold of 100 projects, which is the maximum amount of items the GitLab API will return at once. In order to fetch all results, I have discovered that the base PHP GitLab API library exposes a mechanism to page over all results: https://github.com/GitLabPHP/Client#example-with-pager

How can this be used with this package? My guess is that I would have to get the underlying client instance like this:

```php
/** @var \GrahamCampbell\GitLab\GitLabManager $gitLabManager */

$pager = new \GitLab\ResultPager($gitLabManager->connection());
```

I propose that we either:
- document this usage
- add a helper method `pager(): \GitLab\ResultPager` to `\GrahamCampbell\GitLab\GitLabManager`

Open for better suggestions, of course.

**Comment by andrey-helldar** [comment]
My GitLabPHP/Client#577 issue also affects this package.

**Comment by andrey-helldar** [comment]
Found a solution.

For example:
```php
<?php

use Gitlab\ResultPager;
use GrahamCampbell\GitLab\GitLabManager;
use Illuminate\Container\Container;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Artisan;

Artisan::command('foo', function () {
    $gitlab = Container::getInstance()->make(GitLabManager::class);
    $pager  = Container::getInstance()->make(ResultPager::class);

    $project_id = 10;
    $merge_id   = 2417;

    $commits = $pager->fetchAll($gitlab->mergeRequests(), 'commits', compact('project_id', 'merge_id'));

    dd(
        Arr::pluck($commits, 'message')
    );
});
```

![image](https://user-images.githubusercontent.com/10347617/94012798-eddddb80-fdb1-11ea-8bf1-1f95ba6add9d.png)

**Comment by GrahamCampbell** [comment]
> $gitlab->connection()

You can just resolve the connection from the container directly. You shouldn't resolve the manager like that.

**Comment by andrey-helldar** [comment]
> > $gitlab->connection()
> 
> You can just resolve the connection from the container directly. You shouldn't resolve the manager like that.

Exactly! Thank!

Updated the example in case someone else is looking for such a solution.

**Comment by GrahamCampbell** [comment]
That's still not what I meant. Resolve the actual connection class instead of the manager.

**Comment by GrahamCampbell** [comment]
```php
$client = app(Gitlab\Client::class);
$pager = new ResultPager($client);
$commits = $pager->fetchAll($client->mergeRequests(), 'commits', [10, 2417]);
```

Note in particular that the compact was not right either. The keys are ignored, but the order matters.

**Comment by andrey-helldar** [comment]
Or simplify the code even further:

```php
$gitlab = app(GitLabManager::class);
$pager  = app(ResultPager::class);

$commits = $pager->fetchAll($gitlab->mergeRequests(), 'commits', [10, 2417]);
```

This code worked for me.

PS: The GitLabManager allows Laravel to easily use the project.
But I'm too lazy to climb under the hood to see why it is worth calling the end client.

**Comment by GrahamCampbell** [comment]
No, I would not recommend what you have written there. It only works by a querk that the manager behaves like the client via __call and that the client can be resolved by the container to make the pager.

**Comment by spawnia** [comment]
> No, I would not recommend what you have written there. It only works by a querk that the manager behaves like the client via __call and that the client can be resolved by the container to make the pager.

That is not true. `app(ResultPager::class)` resolves a `GitLab\Client` as a dependency of the `ResultPager`. Also, the result of calling `GitlabManager::mergeRequests()` is the same as calling `Client::mergeRequests()`.
Instantiating the `ResultPager` with anything other than a `GitLab\Client` can not happen because of the typehint in its constructor.

Anyways, @GrahamCampbell what do you think about my original suggestions:

> I propose that we either:
> - document this usage
> - add a helper method pager(): \GitLab\ResultPager to \GrahamCampbell\GitLab\GitLabManager

Having a canonical example in the docs or a helper would be nice. As evidenced by this issue, correct usage is not immediately obvious.

**Comment by GrahamCampbell** [comment]
> app(ResultPager::class) resolves a GitLab\Client as a dependency of the ResultPager.

Yes, but I never intended people to do that. It is only by chance that you get the same instance of the client. That behaviour is not guarenteed, and certainly if you get a different connection than the default from the manager, that code breaks.

**Comment by GrahamCampbell** [comment]
Usage is already documented in the upstream package. You get a client instance (as documented in the readme of this package), and then pass it to a new result pager (as documented upstream, as in my above example).

**Comment by andrey-helldar** [comment]
**My code:**

![image](https://user-images.githubusercontent.com/10347617/94260377-bc434c80-ff38-11ea-95fe-206a7c679b0a.png)

**Graham's code:**

![image](https://user-images.githubusercontent.com/10347617/94260553-117f5e00-ff39-11ea-9509-20c54aa539b9.png)

Yes you are right. It makes no sense to use an additional wrapper :) Thanks!

**Comment by GrahamCampbell** [comment]
No, my code has `$pager = new ResultPager($client);`. It is very important that the container is not used.

**Comment by andrey-helldar** [comment]
> No, my code has `$pager = new ResultPager($client);`. It is very important that the container is not used.

Hmm... I tried to do it nicely :)

**Comment by spawnia** [comment]
Fine. Thanks everyone for the discussion. This issue should have plenty of information for those who need it.

**Comment by jazerix** [comment]
```php
$client = app(Gitlab\Client::class);
$pager  = new ResultPager($client, 100);
$subGroups = ($pager->fetchAll($client->groups(), 'subgroups', [47, ['all_available' => true]]));
```

Doesn't work when working within commands. When I resolve `Gitlab\Client` from the container, I'm getting the default instance, that referes to gitlab.com and not my own server instance. Weirdly, it works if I do it within the `web.php` file.

For now, I've been forced to do the following:
```php
$client = app(Gitlab\Client::class);
$client->setUrl(config('gitlab.connections.main.url'));
$client->authenticate(config('gitlab.connections.main.token'), 'http_token');
$pager = new ResultPager($client, 100);
```
Which is anything but pretty :/
