### ISSUE TITLE
Self hosted Gitlab

### ISSUE THREAD

**Issue by MatasElectronics** [GrahamCampbell/Laravel-GitLab#3]
We've recently switched to this package for working with the Gitlab API. But it seems that this package is not really designed to use with a self hosted Gitlab instance? There is no configuration where we can specify our Gitlab URL. Only thing we can do is use the `->setUrl()` method everytime, this doesn't really seem like a nice solution.

Am I missing some configuration step?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I think this package is missing the ability to configure that at present. I can certainly add this to this package later this week.

**Comment by MatasElectronics** [comment]
That would be wonderful!

**Comment by GrahamCampbell** [comment]
@MatasElectronics I've added the option to specify the base url in the config now. Please try master and let me know if it works. The new field is called `'url'`.

**Comment by MatasElectronics** [comment]
@GrahamCampbell Tried it out and seems to work perfectly! Thanks a lot

**Comment by GrahamCampbell** [comment]
v1.4.0 has been tagged. :)

**Comment by MatasElectronics** [comment]
Thanks!
