### ISSUE TITLE
Incorrect dependency versioning

### ISSUE THREAD

**Issue by andrey-helldar** [GrahamCampbell/Laravel-GitLab#30]
The composer.json file now defines the installation of versions [10.0.*](https://github.com/GrahamCampbell/Laravel-GitLab/blob/4.0/composer.json#L18), While the most recent version of the `m4tthumphrey/php-gitlab-api` package is [10.1.1](https://github.com/GitLabPHP/Client/releases).

**Comment by GrahamCampbell** [comment]
Thanks for the issue. I'm aware of this, and just haven't got around to a new minor release over on this package.

**Comment by andrey-helldar** [comment]
Ah, I got it. Thanks! 👍

**Comment by GrahamCampbell** [comment]
New releases are out now.

**Comment by andrey-helldar** [comment]
Updated. Thanks!
