### ISSUE TITLE
Limits is set to 20 for each request?

### ISSUE THREAD

**Issue by altantosun** [GrahamCampbell/Laravel-GitLab#32]
Hi @GrahamCampbell – thanks for the project.

`$projects = GitLab::projects()->all();`
For this request I get is an array with 20 elements only – is it limited? It should be clearly more than that.
Same `groups`, `Issues`, `mergeRequests`, `namespaces` and `users`

Am I missing something?

Thank you.

**Comment by GrahamCampbell** [comment]
You need to use the result pager. There's an example on the upstream README: https://github.com/GitLabPHP/Client#example-with-pager.
