### ISSUE TITLE
Missing endpoint

### ISSUE THREAD

**Issue by danijelk** [GrahamCampbell/Laravel-GitLab#34]
I was looking through the code but can't see if there is a way to mix the classes, if not we might be able to provide a PR with the missing function in Groups.php class.

Basically this is currently missing https://docs.gitlab.com/ee/api/merge_requests.html#list-group-merge-requests
Which is essentially a mix of the Groups.php and MergeRequests.php?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Please feel free to open a PR on the upstream repo (https://github.com/GitLabPHP/Client). Alternatively, you can email me for a quote to get it implemented. :)
