### ISSUE TITLE
MergeRequest API. Not all attributes are supported.

### ISSUE THREAD

**Issue by michal-bursik** [GrahamCampbell/Laravel-GitLab#39]
**PHP version**: 7.4.3 (hint: `php --version`)

**Description**
According to: [gitlab docs](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests) merge requests are can be filtered by reviewer_id && reviewer_username. Options resolver does not know those attributes.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Please feel free to submit a PR to https://github.com/GitLabPHP/Client. :)
