### ISSUE TITLE
SSL path for Guzzle

### ISSUE THREAD

**Issue by fusiondesign** [GrahamCampbell/Laravel-GitLab#4]
Guzzle, and thereby curl do not like SSL domains being accessed that aren't known Certificate Authorities.

In the past I could do this:
```
$options = [
	'verify' => '/var/www/laravel/storage/certs/UserTrust.pem',
];

$client = new \GuzzleHttp\Client();

$client->get('https://randomssldomain.com', $options);
```

How could I add the 'verify' flag to the underlying Guzzle6 adapter configuration to use your library?

**Comment by GrahamCampbell** [comment]
The HTTP library should be able to automatically locate a good CA list from your system. Are you having trouble connecting to github.com, or do you just want to be able to easily customize this?

**Comment by fusiondesign** [comment]
I work for a major university and our CA is not a well known signer. We sign our own certificates under a name that is not on very many CA lists.

**Comment by fusiondesign** [comment]
I attempted to skirt the underlying libraries and I don't think this is fixable here, so I posted another question in https://github.com/m4tthumphrey/php-gitlab-api/issues/316

unless you know of a way?

This is what I have so far:
```php
$guzzle = GuzzleAdapter::createWithConfig([
	'base_uri' => 'https://my.gitlab.server/',
	'verify' => '/var/www/laravel/storage/certs/UserTrust.pem',
]);

$gitlab = Gitlab\Client::createWithHttpClient($guzzle)
		->authenticate(config('gitlab.token'), Gitlab\Client::AUTH_URL_TOKEN);

// Works
dd($gitlab->getHttpClient()->get('https://my.gitlab.server/api/v4/projects'));

// Does not work
dd($gitlab->api('projects')->all());
```

**Comment by fusiondesign** [comment]
The first dd() work while the second does not. I know you are just wrapping what is in my example, but being able to specify the 'verify', 'cert', or 'ssl_cert' parameters would help immensely even though our use-case is really only the 'verify' guzzle param.

**Comment by GrahamCampbell** [comment]
Ok, so `$gitlab = Gitlab\Client::createWithHttpClient($guzzle)` is totally bypassing the factory in this package, however, it's odd that your second example doesn't work, since it should just be calling `getHttpClient` in the same way as you did in the 1st example. Are you sure you didn't get objects mixed up?

**Comment by GrahamCampbell** [comment]
Oh, I think the second example didn't work because the base url is messed up. You shouldn't set it on guzzle like that. I'll reply to your other thread.

**Comment by GrahamCampbell** [comment]
With regards to this project itself, I suppose we could support setting the http client to use, on the factory.

**Comment by fusiondesign** [comment]
Yeah it was just tough tracing all the classes to bypass that layer and access the underlying guzzle instance. Maybe if the config had an array that begins empty, and if it has any keys in it - it could auto map to the underlying instance of Guzzle and run setUrl against the object automatically if a 'url' is set and guzzle has the base_uri param (Guzzle 6 param). I could probably submit a PR with this new knowledge if you would like.

**Comment by fusiondesign** [comment]
You saved my day. I spent all day tracing your projects and then the project it wrapped but it was fun :)
