### ISSUE TITLE
Group->MergeRequest API missing.

### ISSUE THREAD

**Issue by michal-bursik** [GrahamCampbell/Laravel-GitLab#40]
**Description**
According to [gitlab docs](https://docs.gitlab.com/ee/api/merge_requests.html#list-group-merge-requests) it's possible to list merge requests of given group.

**Example**
```php
$this->gitLab->groups()->mergeRequests($group['id'])->all()
```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Please feel free to submit a PR to https://github.com/GitLabPHP/Client. :)
