### ISSUE TITLE
Support m4tthumphrey/php-gitlab-api 11.8

### ISSUE THREAD

**Issue by spawnia** [GrahamCampbell/Laravel-GitLab#41]
Hi @GrahamCampbell, thanks for releasing https://github.com/GitLabPHP/Client/releases/tag/11.8.0

It would be nice to have a version of this library that allows it. Given that the project adheres to Semantic Versioning, the constraint could be loosened to `^11.6`: https://github.com/GitLabPHP/Client/blob/38380c933ada8fd2099bc611f0de23c339cdb04a/CHANGELOG.md?plain=1#L6

**Comment by GrahamCampbell** [comment]
Support for 11.7 and higher was delayed because of the version bump to PHP 7.4. We now support this, as of version 6.0.0.
