### ISSUE TITLE
Support for php8.2 and laravel 10

### ISSUE THREAD

**Issue by tocsa** [GrahamCampbell/Laravel-GitLab#43]
Would be nice, to keep up with new versions

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I am looking into this now. [Sponsoring me](https://github.com/sponsors/GrahamCampbell) can help me prioritize OSS work. I am spread thin across many open source projects including Guzzle.

**Comment by m-bosch** [comment]
> Thanks for getting in touch. I am looking into this now. [Sponsoring me](https://github.com/sponsors/GrahamCampbell) can help me prioritize OSS work. I am spread thin across many open source projects including Guzzle.

have you any idea / estimate when this will be?

**Comment by GrahamCampbell** [comment]
[v7.0.0](https://github.com/GrahamCampbell/Laravel-GitLab/releases/tag/v7.0.0) is now released. 🎉
