### ISSUE TITLE
Support for psr/http-message 2.0

### ISSUE THREAD

**Issue by asivaneswaran** [GrahamCampbell/Laravel-GitLab#44]
Support for the version 11.10 is needed so we can have access to http-message 2.0

**Comment by Oleksandr-Moik** [comment]
Ping-pong) @GrahamCampbell 

Please, add support for `m4tthumphrey/php-gitlab-api:11.10.*` ([11.10](https://github.com/GitLabPHP/Client/releases/tag/11.10.0)) which gives access to `http-message:2.0`

**Comment by curunoir** [comment]
Hello it would be nice. Thanks for all the work anyway.

**Comment by GrahamCampbell** [comment]
Fixed. :)
