### ISSUE TITLE
Laravel 11 support coming?

### ISSUE THREAD

**Issue by bartdenhoed** [GrahamCampbell/Laravel-GitLab#47]
Hi there,
When can we expect this package updated for Laravel 11?

**Comment by Hackbard** [comment]
Need Laravel 11 too.
Can we help with it?

**Comment by zepfietje** [comment]
You could create a PR similar to this https://github.com/GrahamCampbell/Laravel-GitHub/pull/158, @Hackbard. 🙂

**Comment by GrahamCampbell** [comment]
Yes, today. 🎉
