### ISSUE TITLE
Need to update project due to Framework update

### ISSUE THREAD

**Issue by AndyMac2508** [GrahamCampbell/Laravel-GitLab#6]
Hi i have recently tried to install your package, however a new dependency on Laravel called Nexmo seems to be conflicting with your composer require. Any help would be appreciated.

**Comment by GrahamCampbell** [comment]
What's the conflict?

**Comment by yevhenlisovenko** [comment]
I've got the same issue: http://awescode.com/screenshots/awes_io___www_awes_io__-_____config_app_php__awes_io__21BEA446.png

**Comment by yevhenlisovenko** [comment]
found a solution:
`composer require graham-campbell/gitlab php-http/guzzle6-adapter:^1.0`
The installation instructions should be updated on that.
thanks ;)

**Comment by GrahamCampbell** [comment]
I've updated the readme to reference ` php-http/guzzle6-adapter:^1.1`.

**Comment by GrahamCampbell** [comment]
NB Same issue as https://github.com/BitbucketAPI/Client/issues/18.
