### ISSUE TITLE
Guzzle client build error 

### ISSUE THREAD

**Issue by AndyMac2508** [GrahamCampbell/Laravel-GitLab#7]
Hi firstly thanks for dealing with my last issue so rapidly. Sadly after successfully installing the package and registering the service provider and alias as well as creating and configuring the git-lab config file I am now getting the following error.

![error](https://user-images.githubusercontent.com/16047056/49813461-626f9380-fd5f-11e8-819e-88a9834158e6.png)

I have gone down the rabbit hole for a while and I think its losing the config at some point. Or that i have done some sort of rookie mistake :) .

**Comment by AndyMac2508** [comment]
after further review i think it might actually be a problem with the dependency package you made the wrapper for 'm4tthumphrey/php-gitlab-api'

**Comment by GrahamCampbell** [comment]
What version of the guzzle package have you installed?

**Comment by AndyMac2508** [comment]
The one that you added to the readme 
composer require graham-campbell/gitlab php-http/guzzle6-adapter:^1.1

**Comment by GrahamCampbell** [comment]
Hmm, I can't replicate this.

**Comment by GrahamCampbell** [comment]
Oh, worked it out. You ave installed `1.1` instead of `^1.1`. Version 1.1.0 has this exact bug in it. 1.1.1 fixes it: https://github.com/php-http/guzzle6-adapter/compare/v1.1.0...v1.1.1.

**Comment by azeos** [comment]
I had the same problem and I copy pasted the composer line that's in the readme:

`composer require graham-campbell/gitlab php-http/guzzle6-adapter:^1.1`

But in composer.json appeared as `"php-http/guzzle6-adapter": "1.1"`. Maybe the above line is not the correct syntax.
