### ISSUE TITLE
'all()' methods do not seem to fetch all from API

### ISSUE THREAD

**Issue by dstepe** [GrahamCampbell/Laravel-GitLab#8]
My apologies if I've missed this functionality, but I don't see how to make the `all()` methods return paged results from the GitLab API. The php-gitlab-api project provides a ResultPager class which fetches all pages, but that does not appear to be used.

For example, this fetches only the first page of my projects:

```php
$projectData = $this->gitLabManager->projects()->all();
```
I can explicitly use a pager to get all:

```php
$client = $this->gitLabManager->connection();
$pager = new \Gitlab\ResultPager($client);
$projectData = $pager->fetchAll($client->api('projects'),'all');
```
Is there a way to have the `all()` method do the same?

**Comment by GrahamCampbell** [comment]
Unfortunately not. You'll have to use the pager, or write your own wrapper around it. I'd suggest raising further concerns with the upstream package, to see if they are interested in writing some kind of abstraction layer on top. :)
